Vagrant.configure("2") do |config|
  
    config.vm.box = "bento/ubuntu-22.04"
  
    config.vm.synced_folder '.', '/vagrant', disabled: true
  
    config.vm.define "controlplane" do |host1|
      host1.vm.hostname = "controlplane"
      host1.vm.network "private_network", ip: "192.168.56.124"
      host1.vm.network "forwarded_port", guest: 22, host: 1124
    end
  
    config.vm.define "worker1" do |host2|
      host2.vm.hostname = "worker1"
      host2.vm.network "private_network", ip: "192.168.56.125"
      host2.vm.network "forwarded_port", guest: 22, host: 1125
    end
  
    config.vm.define "worker2" do |host3|
      host3.vm.hostname = "worker2"
      host3.vm.network "private_network", ip: "192.168.56.126"
      host3.vm.network "forwarded_port", guest: 22, host: 1126
    end
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
  
  end
