
- name: HAProxy & Keepalived installation
  hosts: haproxy-nodes
  become: yes
  any_errors_fatal: true

  tasks:
    - name: Run system updates
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
    
    - name: Install OS dependencies
      ansible.builtin.apt:
        pkg:
        - keepalived
        - haproxy

    - name: Keepalived configuration script
      ansible.builtin.copy:
        dest: /etc/keepalived/check_apiserver.sh
        content: |
          #!/bin/sh

          errorExit() {
            echo "*** $@" 1>&2
            exit 1
          }

          curl --silent --max-time 2 --insecure https://localhost:6443/ -o /dev/null || errorExit "Error GET https://localhost:6443/"
          if ip addr | grep -q {{ haproxy_virtual_ip }}; then
            curl --silent --max-time 2 --insecure https://{{ haproxy_virtual_ip }}:6443/ -o /dev/null || errorExit "Error GET https://{{ haproxy_virtual_ip }}:6443/"
          fi
        mode: '0755'

    - name: Keepalived conf file configuration
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_script check_apiserver {
            script "/etc/keepalived/check_apiserver.sh"
            interval 3
            timeout 10
            fall 5
            rise 2
            weight -2
          }

          vrrp_instance VI_1 {
              state BACKUP
              interface eth0
              virtual_router_id 2
              priority 100
              advert_int 5
              authentication {
                  auth_type PASS
                  auth_pass mysecret
              }
              virtual_ipaddress {
                  {{ haproxy_virtual_ip }}
              }
              track_script {
                  check_apiserver
              }
          }
        mode: '0644'

    - name: Enable & start keepalived service
      ansible.builtin.shell: |
        systemctl enable --now keepalived

    - name: HAproxy conf
      ansible.builtin.copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          frontend kubernetes-frontend
            bind *:6443
            mode tcp
            option tcplog
            default_backend kubernetes-backend

          backend kubernetes-backend
            option httpchk GET /healthz
            http-check expect status 200
            mode tcp
            option ssl-hello-chk
            balance roundrobin
              server kubernetes-control-plane-node-1 {{ hostvars['kubernetes-control-plane-node-1']['ansible_host'] }}:6443 check fall 3 rise 2
              server kubernetes-control-plane-node-2 {{ hostvars['kubernetes-control-plane-node-2']['ansible_host'] }}:6443 check fall 3 rise 2
              server kubernetes-control-plane-node-3 {{ hostvars['kubernetes-control-plane-node-3']['ansible_host'] }}:6443 check fall 3 rise 2
        mode: '0644'

    - name: Enable & restart haproxy service
      ansible.builtin.shell: |
        systemctl enable haproxy && systemctl restart haproxy